### ISSUE TITLE
Comment on "Debugging Vim by example"

### ISSUE THREAD

**Issue by Konfekt** [codeinthehole/codeinthehole.hugo#13]
Article: Debugging Vim by example
URL: https://codeinthehole.com/tips/debugging-vim-by-example/

Thanks for the thorough article. We must be glad that https://github.com/Konfekt/FastFold wasn't installed, but now it could be a viable alternative to the proposed `let g:vim_markdown_folding_disabled = 1`. (The same documented slowdown, for other file types as well, was what led me to writing it).

**Comment by codeinthehole** [comment]
Thanks for the tip - I'll try `FastFold` out.
