### ISSUE TITLE
Comment on "Continuously rebuild your project"

### ISSUE THREAD

**Issue by PoolloverNathan** [codeinthehole/codeinthehole.hugo#16]
Article: Continuously rebuild your project
URL: https://codeinthehole.com/tips/continuously-re-build-your-project/

The pitfall link died. Please fix!

**Comment by codeinthehole** [comment]
Thanks! Fixed in https://github.com/codeinthehole/codeinthehole.hugo/commit/a21f16b67e5e282a327db5c70d860c557806b332
