### ISSUE TITLE
git-pre-commit-tips.md - important hint about stashing

### ISSUE THREAD

**Issue by IzzySoft** [codeinthehole/codeinthehole.hugo#18]
> Ensure that code that isn’t part of the prospective commit isn’t tested within your pre-commit script. This is missed by many sample pre-commit scripts but is easily acheived with `git stash`:

One reason why this is not done could be that stashing breaks hard links if a hard-linked file is being stashed – and does not restore them afterwards. That should be pointed out before someone learns it "the hard way". You can verify that yourself by creating a hard link (`ln file1 file2`), check with `stat file1`, change file1, stash it, pop it and then check with `stat file1` again: while `stat` will initially report "Links: 2", you'll end up with "Links: 1" – the hard link is gone, the two copies will go "out of sync" from now on.¹

Of course, if there's a solution to that, please propose!

¹ <sub>PS: in detail also [mentioned here](http://git.661346.n2.nabble.com/git-stash-destroys-hard-links-td7559691.html).</sub>

**Comment by mlt** [comment]
Is it ever a good idea to use hardlinks with git?

That aside, I think there is an asterisk missing
```
if [[ $STASHES == "$STASH_NAME" ]]; then
```
I think it should have `== *"$STASH_NAME"`.

Also...perhaps it is worth mentioning `--include-untracked`.

**Comment by IzzySoft** [comment]
> Is it ever a good idea to use hardlinks with git?

That's a completely different matter, but I was expecting that question somehow. Sure, if you have identical files in multiple projects, you should be using submodules instead. But a) is handling submodules another level of complexity, and b) a little overkill for a single file.

I've instead chosen to let the pre-commit only deal with files which are staged. *For my case* that works fine. But of course, it might miss to track some (potentially broken) dependencies.
