### ISSUE TITLE
Comment on "The most important command-line tip - incremental history searching with .inputrc"

### ISSUE THREAD

**Issue by Mugane** [codeinthehole/codeinthehole.hugo#22]
What key/character is "\e[A" and what is "\e[B"?

Article: The most important command-line tip - incremental history searching with .inputrc
URL: https://codeinthehole.com/tips/the-most-important-command-line-tip-incremental-history-searching-with-inputrc/

**Comment by codeinthehole** [comment]
The `\e` is the ANSI escape character and `[A` maps to the "up" key. `\e[B` is for the "down" key. 

Hope that helps.
