### ISSUE TITLE
Comment on "Tips for using a git pre-commit hook"

### ISSUE THREAD

**Issue by joswr1ght** [codeinthehole/codeinthehole.hugo#23]
Article: Tips for using a git pre-commit hook
URL: https://codeinthehole.com/tips/tips-for-using-a-git-pre-commit-hook/

There is a typo in the test for stash name which prevents the stashed files from being `pop`'d:

```
if [[ $STASHES == "$STASH_NAME" ]]; then
  git stash pop -q
fi
```

This `if` statement checks for an exact match `$STASHES == "$STASH_NAME"`, which will never be true due to other output in the `git stash list` output. I think you mean to use the `=~` operator instead:

```
if [[ $STASHES =~ "$STASH_NAME" ]]; then
  git stash pop -q
fi
```

This works as intended, using the regular expression `"$STASH_NAME"` to applied to the `git stash list` output.

**Comment by codeinthehole** [comment]
Thanks - I've fixed this another comment:
https://github.com/codeinthehole/codeinthehole.hugo/commit/09343d4b39042883efb8d6b59504c962f202c400
