### ISSUE TITLE
Comment on "Solving MySQL connection problems caused by a dead name server"

### ISSUE THREAD

**Issue by derak-kilgo** [codeinthehole/codeinthehole.hugo#3]
Article: Solving MySQL connection problems caused by a dead name server
URL: http://codeinthehole.com/tips/solving-mysql-connection-problems-caused-by-a-dead-name-server/

You could also modify the /etc/hosts to include the hosts ip address(es) of your mysql servers and clients. This was the quickest solution for me while IT worked on the broken DNS server.
This article was super helpful in figuring out what was going on. Many thanks.

**Comment by codeinthehole** [comment]
Glad it was of help
