### ISSUE TITLE
Comment on "Why your Django models are fat"

### ISSUE THREAD

**Issue by tartley** [codeinthehole/codeinthehole.hugo#5]
Article: Why your Django models are fat
URL: http://codeinthehole.com/lists/why-your-models-are-fat/

Splendid stuff. I like to call my business logic module or package "usecase", the idea being that the topmost entry-points correspond to usecases.

**Comment by codeinthehole** [comment]
Our application architecture at Octopus has evolved that way too - see https://github.com/octoenergy/conventions/blob/master/patterns.md#application-layer-conventions
