### ISSUE TITLE
Comment on "Using the silver searcher with Vim"

### ISSUE THREAD

**Issue by tartley** [codeinthehole/codeinthehole.hugo#6]
Article: Using the silver searcher with Vim
URL: http://codeinthehole.com/tips/using-the-silver-searcher-with-vim/

I already have searches that are massively faster than 'ack', because I use grep. Despite the misleading marketing, ack had always been slower than grep - it just ignores more files by default.

I defined a list of grep "excludes" once, in the 1990s, and have tweaked it from time to time since. Coupled with Vim plugins like fzf (which also augments things such as bash command history searches.) It's really rad.

I'm disappointed that ag doesn't cite performance comparisons with grep in it's readme. As far as can tell, the only thing it does that grep doesn't do is use multiple threads. This is curious to me, because I would have expected "searching through files"to be the classic example of a problem that was IO bound. So does using multiple threads really help? I'm happy to believe it does, if the evidence points that way.

**Comment by codeinthehole** [comment]
Have you switched to ripgrep more recently? (only just discovered these blog comments btw - should have been watching this repo more closely)
