### ISSUE TITLE
Comment on "Tips for using a git pre-commit hook"

### ISSUE THREAD

**Issue by geekygrappler** [codeinthehole/codeinthehole.hugo#9]
Article: Tips for using a git pre-commit hook
URL: http://codeinthehole.com/tips/tips-for-using-a-git-pre-commit-hook/

Hey, the symlink to `pre-commit.sh` didn't work for me on mac. Following this article: https://khangdinh.wordpress.com/2014/05/15/git-hook-dont-seem-to-follow-symlinks/

The reason was `git` user not having permission to execute that shell file, so I granted permission with `chmod 777 pre-commit.sh`. Different solution to that article, but worked for me.

**Comment by codeinthehole** [comment]
Good to know
